/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aed;

import org.openstreetmap.gui.jmapviewer.Coordinate;
import org.openstreetmap.gui.jmapviewer.JMapViewer;
import org.openstreetmap.gui.jmapviewer.MapMarkerDot;
import org.openstreetmap.gui.jmapviewer.MapPolygonImpl;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author enzof
 */
public class TelaAED extends javax.swing.JFrame {
    
    private JMapViewer map;
    private List<Lugar> lugares = new ArrayList<>();
    private List<Rota> rotas = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAED.class.getName());

    /**
     * Creates new form TelaAED
     */
    public TelaAED() {
        initComponents();
        map = new JMapViewer();
        map.setZoom(5);
        map.setDisplayPosition(new Coordinate(-15.7801, -47.9292), 4); // Centraliza no Brasil

        // 2. Adiciona os listeners
        map.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    Point p = e.getPoint();
                    Coordinate coord = (Coordinate) map.getPosition(p);
                    
                    // Este método será copiado no próximo passo
                    cadastrarLugar(coord); 
                }
            }
            
        });

        // 3. ADICIONA O MAPA NO PAINEL DO DESIGN
        // (panelMapa foi o nome que você deu ao JPanel no modo Design)
        panelMapa.setLayout(new BorderLayout());
        panelMapa.add(map, BorderLayout.CENTER);
        carregarLugaresIniciais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapa = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jButton1.setText("Cadastrar Rota");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("jButton2");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 612, Short.MAX_VALUE))
            .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrarRota();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAED().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panelMapa;
    // End of variables declaration//GEN-END:variables
    private void cadastrarLugar(Coordinate coord) {
        String nome = JOptionPane.showInputDialog(this, "Nome do lugar:");
        if (nome == null || nome.isEmpty()) return;

        String[] tipos = {"Polícia", "Bombeiros", "Médicos", "Lógistica"};
        String tipo = (String) JOptionPane.showInputDialog(
                this, "Selecione o tipo:",
                "Tipo do lugar",
                JOptionPane.PLAIN_MESSAGE,
                null,
                tipos,
                tipos[0]
        );

        Lugar lugar = new Lugar(nome, tipo, coord);
        lugares.add(lugar);

        // Marcador no mapa
        map.addMapMarker(new MapMarkerDot(nome, coord));

        JOptionPane.showMessageDialog(this,
                "Lugar cadastrado:\n" + lugar);
    }
    private void cadastrarRota() {
        if (lugares.size() < 2) {
            JOptionPane.showMessageDialog(this,
                    "É necessário pelo menos 2 lugares cadastrados.");
            return;
        }

        Lugar origem = (Lugar) JOptionPane.showInputDialog(
                this, "Selecione o lugar de origem:",
                "Origem",
                JOptionPane.PLAIN_MESSAGE,
                null,
                lugares.toArray(),
                lugares.get(0)
        );

        Lugar destino = (Lugar) JOptionPane.showInputDialog(
                this, "Selecione o lugar de destino:",
                "Destino",
                JOptionPane.PLAIN_MESSAGE,
                null,
                lugares.toArray(),
                lugares.get(0)
        );

        if (origem == null || destino == null || origem.equals(destino)) {
            JOptionPane.showMessageDialog(this, "Seleção inválida.");
            return;
        }

        double distancia = calcularDistancia(origem.getCoord(), destino.getCoord());
        Rota rota = new Rota(origem, destino, distancia);
        rotas.add(rota);

        // Desenhar a rota no mapa
        List<Coordinate> coords = new ArrayList<>();
        coords.add(origem.getCoord());
        coords.add(destino.getCoord());
        map.addMapPolygon(new MapPolygonImpl(coords));

        JOptionPane.showMessageDialog(this,
                "Rota cadastrada:\n" + rota);
    }
    private double calcularDistancia(Coordinate c1, Coordinate c2) {
        final double R = 6371.0; // raio da Terra em km
        double lat1 = Math.toRadians(c1.getLat());
        double lon1 = Math.toRadians(c1.getLon());
        double lat2 = Math.toRadians(c2.getLat());
        double lon2 = Math.toRadians(c2.getLon());

        double dlat = lat2 - lat1;
        double dlon = lon2 - lon1;

        double a = Math.sin(dlat / 2) * Math.sin(dlat / 2) +
                Math.cos(lat1) * Math.cos(lat2) *
                        Math.sin(dlon / 2) * Math.sin(dlon / 2);

        double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

        return R * c;
    }
    //gitteste
    private void carregarLugaresIniciais() {
        // Você pode adicionar quantos lugares quiser aqui.
        // Usei coordenadas de exemplo em Brasília, já que o mapa centraliza lá.

        // Exemplo 1: Hospital
        Coordinate c1 = new Coordinate(-15.7997, -47.8938); // Coordenada do Hospital de Base
        Lugar hospital = new Lugar("Hospital de Base", "Hospital", c1);
        
        // Adiciona na lista de lugares (para usar nas rotas)
        lugares.add(hospital); 
        // Adiciona o marcador no mapa
        map.addMapMarker(new MapMarkerDot(hospital.getNome(), hospital.getCoord()));

        
        // Exemplo 2: Ponto Turístico
        Coordinate c2 = new Coordinate(-15.7996, -47.8645); // Coordenada do Congresso Nacional
        Lugar congresso = new Lugar("Congresso Nacional", "Ponto Turístico", c2);
        
        lugares.add(congresso);
        map.addMapMarker(new MapMarkerDot(congresso.getNome(), congresso.getCoord()));

        
        // Exemplo 3: Restaurante
        Coordinate c3 = new Coordinate(-15.8052, -47.8777); // Coordenada de um restaurante
        Lugar restaurante = new Lugar("Restaurante X", "Restaurante", c3);
        
        lugares.add(restaurante);
        map.addMapMarker(new MapMarkerDot(restaurante.getNome(), restaurante.getCoord()));
        
        // Mensagem (opcional)
        logger.info("Lugares iniciais carregados.");
    }
    
}
