/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aed;

import org.openstreetmap.gui.jmapviewer.Coordinate;
import org.openstreetmap.gui.jmapviewer.JMapViewer;
import org.openstreetmap.gui.jmapviewer.MapMarkerDot;
import org.openstreetmap.gui.jmapviewer.MapPolygonImpl;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.*; // Importa Map, List, ArrayList, Set, HashMap, etc.

/**
 *
 * @author enzof
 */
public class TelaAED extends javax.swing.JFrame {
    
    private JMapViewer map;
    private List<Lugar> lugares = new ArrayList<>();
    private List<Rota> rotas = new ArrayList<>();
    // Adicione logo abaixo de: private List<Rota> rotas...
    private boolean modoSelecaoDesastre = false; 
    private String tipoDesastreAtual = "";
    private Grafo grafoCidade = new Grafo(); // Seu objeto Grafo
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAED.class.getName());

    /**
     * Creates new form TelaAED
     */
    public TelaAED() {
        initComponents();
        map = new JMapViewer();
        map.setZoom(5);
        map.setDisplayPosition(new Coordinate(-12.6710, -39.1005), 14); // Zoom 14 para ver as ruas 
        // 2. Adiciona os listeners
        map.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    Point p = e.getPoint();
                    Coordinate coord = (Coordinate) map.getPosition(p);
                    
                    if (modoSelecaoDesastre) {
                        // Se clicou para marcar desastre
                        processarDesastre(coord, tipoDesastreAtual);
                        modoSelecaoDesastre = false; // Reseta o modo
                    } else {
                        // Se clicou para cadastrar um lugar novo (comportamento antigo)
                        cadastrarLugar(coord); 
                    } 
                }
            }
            
        });

        // 3. ADICIONA O MAPA NO PAINEL DO DESIGN
        // (panelMapa foi o nome que você deu ao JPanel no modo Design)
        panelMapa.setLayout(new BorderLayout());
        panelMapa.add(map, BorderLayout.CENTER);
        carregarLugaresIniciais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapa = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jButton1.setText("Cadastrar Rota");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Cadastrar Desastre");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 612, Short.MAX_VALUE))
            .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrarRota();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Pergunta a descrição/tipo do desastre
        String[] opcoes = {"Incêndio", "Acidente de Trânsito", "Resgate", "Outros"};
        String escolha = (String) JOptionPane.showInputDialog(
                this, "Qual o tipo da ocorrência?", "Reportar Desastre",
                JOptionPane.WARNING_MESSAGE, null, opcoes, opcoes[0]);

        if (escolha != null) {
            this.tipoDesastreAtual = escolha;
            this.modoSelecaoDesastre = true; // Ativa o modo de espera pelo clique
            JOptionPane.showMessageDialog(this, 
                "Agora CLIQUE no mapa onde ocorreu o desastre (" + escolha + ").");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAED().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panelMapa;
    // End of variables declaration//GEN-END:variables
    private void cadastrarLugar(Coordinate coord) {
        String nome = JOptionPane.showInputDialog(this, "Nome do lugar:");
        if (nome == null || nome.isEmpty()) return;

        String[] tipos = {"Polícia", "Bombeiros", "Médicos", "Lógistica"};
        String tipo = (String) JOptionPane.showInputDialog(
                this, "Selecione o tipo:",
                "Tipo do lugar",
                JOptionPane.PLAIN_MESSAGE,
                null,
                tipos,
                tipos[0]
        );

        Lugar lugar = new Lugar(nome, tipo, coord);
        lugares.add(lugar);

        // Marcador no mapa
        map.addMapMarker(new MapMarkerDot(nome, coord));

        JOptionPane.showMessageDialog(this,
                "Lugar cadastrado:\n" + lugar);
    }
    private void cadastrarRota() {
        if (lugares.size() < 2) {
            JOptionPane.showMessageDialog(this,
                    "É necessário pelo menos 2 lugares cadastrados.");
            return;
        }

        Lugar origem = (Lugar) JOptionPane.showInputDialog(
                this, "Selecione o lugar de origem:",
                "Origem",
                JOptionPane.PLAIN_MESSAGE,
                null,
                lugares.toArray(),
                lugares.get(0)
        );

        Lugar destino = (Lugar) JOptionPane.showInputDialog(
                this, "Selecione o lugar de destino:",
                "Destino",
                JOptionPane.PLAIN_MESSAGE,
                null,
                lugares.toArray(),
                lugares.get(0)
        );

        if (origem == null || destino == null || origem.equals(destino)) {
            JOptionPane.showMessageDialog(this, "Seleção inválida.");
            return;
        }

        double distancia = calcularDistancia(origem.getCoord(), destino.getCoord());
        Rota rota = new Rota(origem, destino, distancia);
        rotas.add(rota);

        // Desenhar a rota no mapa
        List<Coordinate> coords = new ArrayList<>();
        coords.add(origem.getCoord());
        coords.add(destino.getCoord());
        map.addMapPolygon(new MapPolygonImpl(coords));

        JOptionPane.showMessageDialog(this,
                "Rota cadastrada:\n" + rota);
    }
    private double calcularDistancia(Coordinate c1, Coordinate c2) {
        final double R = 6371.0; // raio da Terra em km
        double lat1 = Math.toRadians(c1.getLat());
        double lon1 = Math.toRadians(c1.getLon());
        double lat2 = Math.toRadians(c2.getLat());
        double lon2 = Math.toRadians(c2.getLon());

        double dlat = lat2 - lat1;
        double dlon = lon2 - lon1;

        double a = Math.sin(dlat / 2) * Math.sin(dlat / 2) +
                Math.cos(lat1) * Math.cos(lat2) *
                        Math.sin(dlon / 2) * Math.sin(dlon / 2);

        double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

        return R * c;
    }
    private void carregarLugaresIniciais() {
        // --- COORDENADAS DE CRUZ DAS ALMAS, BA ---
        
        // 1. Equipes (Bases)
        // Local fictício próximo à saída para BR-101
        Lugar baseBombeiros = new Lugar("Bombeiros (BR-101)", "Bombeiros", new Coordinate(-12.6645, -39.1130));
        // Próximo ao centro
        Lugar baseHospital = new Lugar("Hospital (Centro)", "Médicos", new Coordinate(-12.6738, -39.1070)); 
        
        // 2. Pontos de Passagem (Malha Viária da cidade)
        Lugar pracaMatriz = new Lugar("Praça Sen. Temístocles", "Via", new Coordinate(-12.6710, -39.1005));
        Lugar ufrb = new Lugar("Entrada UFRB", "Via", new Coordinate(-12.6600, -39.0900));
        Lugar embrapa = new Lugar("Embrapa", "Via", new Coordinate(-12.6780, -39.1200));
        Lugar rodoviaria = new Lugar("Rodoviária", "Via", new Coordinate(-12.6685, -39.1050));

        // Adiciona visualmente e logicamente
        adicionarLugarNoSistema(baseBombeiros);
        adicionarLugarNoSistema(baseHospital);
        adicionarLugarNoSistema(pracaMatriz);
        adicionarLugarNoSistema(ufrb);
        adicionarLugarNoSistema(embrapa);
        adicionarLugarNoSistema(rodoviaria);

        // --- CONEXÕES REAIS ---
        // Agora não passamos o peso manual. O método calculará a distância em KM.
        
        // Conexões do Hospital
        criarConexao(baseHospital, pracaMatriz);
        criarConexao(baseHospital, rodoviaria);
        
        // Conexões da Rodoviária
        criarConexao(rodoviaria, baseBombeiros);
        criarConexao(rodoviaria, pracaMatriz);
        criarConexao(rodoviaria, embrapa);
        
        // Conexões da UFRB
        criarConexao(ufrb, pracaMatriz);
        criarConexao(ufrb, baseBombeiros); // Via perimetral fictícia

        logger.info("Mapa de Cruz das Almas carregado.");
    }

    // --- Métodos Auxiliares para evitar repetição de código ---

    private void adicionarLugarNoSistema(Lugar l) {
        lugares.add(l); // Lista local
        map.addMapMarker(new MapMarkerDot(l.getNome(), l.getCoord())); // Visual
        grafoCidade.adicionarLugar(l); // Grafo Lógico (Dijkstra)
    }

    private void criarConexao(Lugar origem, Lugar destino) {
        // Calcula a distância real em KM para usar como PESO da aresta
        double distanciaReal = calcularDistancia(origem.getCoord(), destino.getCoord());
        
        // Conecta no Grafo Lógico
        grafoCidade.adicionarRota(origem, destino, distanciaReal);

        // Desenha a linha no Mapa Visual
        List<Coordinate> linha = new ArrayList<>();
        linha.add(origem.getCoord());
        linha.add(destino.getCoord());
        map.addMapPolygon(new MapPolygonImpl(linha));
    }
    
    private void processarDesastre(Coordinate coordDesastre, String descricao) {
        // 1. Identificar tipo de equipe
        String tipoEquipeNecessaria;
        if (descricao.equals("Incêndio") || descricao.equals("Resgate")) {
            tipoEquipeNecessaria = "Bombeiros";
        } else if (descricao.equals("Acidente de Trânsito")) {
            tipoEquipeNecessaria = "Médicos";
        } else {
            tipoEquipeNecessaria = "Logística"; 
        }

        // 2. Achar o nó da malha viária mais próximo do clique
        Lugar noMaisProximo = null;
        double menorDistanciaDoCliqueAoNo = Double.MAX_VALUE;

        for (Lugar l : lugares) {
            double d = calcularDistancia(coordDesastre, l.getCoord());
            if (d < menorDistanciaDoCliqueAoNo) {
                menorDistanciaDoCliqueAoNo = d;
                noMaisProximo = l;
            }
        }

        if (noMaisProximo == null) {
            JOptionPane.showMessageDialog(this, "Erro: O mapa está vazio.");
            return;
        }

        // Adiciona marcador do desastre
        map.addMapMarker(new MapMarkerDot("DESASTRE: " + descricao, coordDesastre));

        // 3. Executar Dijkstra a partir do nó da rua
        Map<Lugar, Double> distanciasPeloGrafo = grafoCidade.executarDijkstra(noMaisProximo);

        // 4. Escolher a melhor equipe SOMANDO as duas distâncias
        Lugar melhorEquipe = null;
        double menorCaminhoTotal = Double.MAX_VALUE;
        double distanciaGrafoFinal = 0;

        for (Map.Entry<Lugar, Double> entrada : distanciasPeloGrafo.entrySet()) {
            Lugar lugarAtual = entrada.getKey();
            double distPeloGrafo = entrada.getValue();

            if (lugarAtual.getTipo().equalsIgnoreCase(tipoEquipeNecessaria)) {
                
                // --- AQUI ESTÁ A LÓGICA QUE VOCÊ PEDIU ---
                // Total = (Equipe -> Nó da Rua) + (Nó da Rua -> Local Exato do Clique)
                double total = distPeloGrafo + menorDistanciaDoCliqueAoNo;
                
                if (total < menorCaminhoTotal) {
                    menorCaminhoTotal = total;
                    melhorEquipe = lugarAtual;
                    distanciaGrafoFinal = distPeloGrafo;
                }
            }
        }

        // 5. Resultado Detalhado
        if (melhorEquipe != null) {
            String msg = String.format("""
                DESASTRE: %s
                Ponto de referência mais próximo: %s
                Distância do clique até a referência: %.2f km
                
                EQUIPE ACIONADA: %s
                Distância da base até a referência (Via Grafo): %.2f km
                ------------------------------------------------
                DISTÂNCIA TOTAL ESTIMADA: %.2f km
                """, 
                descricao, 
                noMaisProximo.getNome(), 
                menorDistanciaDoCliqueAoNo,
                melhorEquipe.getNome(),
                distanciaGrafoFinal,
                menorCaminhoTotal
            );
            
            JOptionPane.showMessageDialog(this, msg);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Nenhuma equipe de " + tipoEquipeNecessaria + " encontrada!");
        }
    }
}
