/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aed;

import org.openstreetmap.gui.jmapviewer.Coordinate;
import org.openstreetmap.gui.jmapviewer.JMapViewer;
import org.openstreetmap.gui.jmapviewer.MapMarkerDot;
import org.openstreetmap.gui.jmapviewer.MapPolygonImpl;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.*; 

/**
 *
 * @author enzof
 */
public class TelaAED extends javax.swing.JFrame {
    
    private Map<java.util.UUID, MapMarkerDot> marcadoresAtivos = new HashMap<>();
    private JMapViewer map;
    private List<Lugar> lugares = new ArrayList<>();
    private List<Rota> rotas = new ArrayList<>();
    private boolean modoSelecaoDesastre = false; 
    private String tipoDesastreAtual = "";
    private HashCentroRecursos hashRecursos = new HashCentroRecursos(); 
    private ArvoreAVL arvoreEquipes = new ArvoreAVL();
    private FilaDeSolicitacoes filaEmergencia = new FilaDeSolicitacoes();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAED.class.getName());
    
    private Grafo grafoCidade = new Grafo(); 

    /**
     * Creates new form TelaAED
     */
    public TelaAED() {
        
        initComponents();
        map = new JMapViewer();
        map.setZoom(5);
        map.setDisplayPosition(new Coordinate(-12.6710, -39.1005), 14); 
        
        map.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    Point p = e.getPoint();
                    Coordinate coord = (Coordinate) map.getPosition(p);
                    
                    if (modoSelecaoDesastre) {                     
                        adicionarNaFila(coord, tipoDesastreAtual);
                        modoSelecaoDesastre = false; // Reseta o modo
                    } else {
                        cadastrarLugar(coord); 
                    } 
                }
            }
            
        });

        panelMapa.setLayout(new BorderLayout());
        panelMapa.add(map, BorderLayout.CENTER);
        carregarLugaresIniciais();
        gerarCentrosRecursosAleatorios();
        
        //testeVisualizacaoAVL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapa = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jButton1.setText("Cadastrar Rota");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Cadastrar Desastre");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Atender");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 470, Short.MAX_VALUE))
            .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrarRota();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String[] opcoes = {"Incêndio", "Acidente de Trânsito", "Resgate", "Outros"};
        String escolha = (String) JOptionPane.showInputDialog(
                this, "Qual o tipo da ocorrência?", "Reportar Desastre",
                JOptionPane.WARNING_MESSAGE, null, opcoes, opcoes[0]);

        if (escolha != null) {
            this.tipoDesastreAtual = escolha;
            this.modoSelecaoDesastre = true; 
            JOptionPane.showMessageDialog(this, 
                "Agora CLIQUE no mapa onde ocorreu o desastre (" + escolha + ").");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        atenderProximaSolicitacao();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAED().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel panelMapa;
    // End of variables declaration//GEN-END:variables
    
    
    private void cadastrarLugar(Coordinate coord) {
        String nome = JOptionPane.showInputDialog(this, "Nome do lugar:");
        if (nome == null || nome.isEmpty()) return;

        String[] tipos = {"Polícia", "Bombeiros", "Médicos", "Lógistica"};
        String tipo = (String) JOptionPane.showInputDialog(
                this, "Selecione o tipo:",
                "Tipo do lugar",
                JOptionPane.PLAIN_MESSAGE,
                null,
                tipos,
                tipos[0]
        );

        Lugar lugar = new Lugar(nome, tipo, coord);
        lugares.add(lugar);

        // Marcador no mapa
        map.addMapMarker(new MapMarkerDot(nome, coord));
        grafoCidade.adicionarLugar(lugar);
        JOptionPane.showMessageDialog(this,
                "Lugar cadastrado:\n" + lugar);
    }
    
    private void cadastrarRota() {
        if (lugares.size() < 2) {
            JOptionPane.showMessageDialog(this,
                    "É necessário pelo menos 2 lugares cadastrados.");
            return;
        }

        Lugar origem = (Lugar) JOptionPane.showInputDialog(
                this, "Selecione o lugar de origem:",
                "Origem",
                JOptionPane.PLAIN_MESSAGE,
                null,
                lugares.toArray(),
                lugares.get(0)
        );

        Lugar destino = (Lugar) JOptionPane.showInputDialog(
                this, "Selecione o lugar de destino:",
                "Destino",
                JOptionPane.PLAIN_MESSAGE,
                null,
                lugares.toArray(),
                lugares.get(0)
        );

        if (origem == null || destino == null || origem.equals(destino)) {
            JOptionPane.showMessageDialog(this, "Seleção inválida.");
            return;
        }

        double distancia = calcularDistancia(origem.getCoord(), destino.getCoord());
        Rota rota = new Rota(origem, destino, distancia);
        rotas.add(rota);

        // Desenhar a rota no mapa
        List<Coordinate> coords = new ArrayList<>();
        coords.add(origem.getCoord());
        coords.add(destino.getCoord());
        map.addMapPolygon(new MapPolygonImpl(coords));
        grafoCidade.adicionarRota(origem, destino, distancia);
        JOptionPane.showMessageDialog(this,
                "Rota cadastrada:\n" + rota);
    }
    
    private double calcularDistancia(Coordinate c1, Coordinate c2) {
        final double R = 6371.0; // raio da Terra em km
        double lat1 = Math.toRadians(c1.getLat());
        double lon1 = Math.toRadians(c1.getLon());
        double lat2 = Math.toRadians(c2.getLat());
        double lon2 = Math.toRadians(c2.getLon());

        double dlat = lat2 - lat1;
        double dlon = lon2 - lon1;

        double a = Math.sin(dlat / 2) * Math.sin(dlat / 2) +
                Math.cos(lat1) * Math.cos(lat2) *
                        Math.sin(dlon / 2) * Math.sin(dlon / 2);

        double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

        return R * c;
    }
    
    private void carregarLugaresIniciais() {
        // --- COORDENADAS DE CRUZ DAS ALMAS, BA ---
        
        // 1. Equipes (Bases)
        Lugar baseBombeiros = new Lugar("Bombeiros (BR-101)", "Bombeiros", new Coordinate(-12.6645, -39.1130));
        Lugar baseHospital = new Lugar("Hospital (Centro)", "Médicos", new Coordinate(-12.6738, -39.1070)); 
        
        // 2. Pontos de Passagem (Malha Viária da cidade)
        Lugar pracaMatriz = new Lugar("Praça Sen. Temístocles", "Via", new Coordinate(-12.6710, -39.1005));
        Lugar ufrb = new Lugar("Entrada UFRB", "Via", new Coordinate(-12.6600, -39.0900));
        Lugar embrapa = new Lugar("Embrapa", "Via", new Coordinate(-12.6780, -39.1200));
        Lugar rodoviaria = new Lugar("Rodoviária", "Via", new Coordinate(-12.6685, -39.1050));

        // Adiciona visualmente e logicamente
        adicionarLugarNoSistema(baseBombeiros);
        adicionarLugarNoSistema(baseHospital);
        adicionarLugarNoSistema(pracaMatriz);
        adicionarLugarNoSistema(ufrb);
        adicionarLugarNoSistema(embrapa);
        adicionarLugarNoSistema(rodoviaria);

        // --- CONEXÕES REAIS ---
        
        // Conexões do Hospital
        criarConexao(baseHospital, pracaMatriz);
        criarConexao(baseHospital, rodoviaria);
        
        // Conexões da Rodoviária
        criarConexao(rodoviaria, baseBombeiros);
        criarConexao(rodoviaria, pracaMatriz);
        criarConexao(rodoviaria, embrapa);
        
        // Conexões da UFRB
        criarConexao(ufrb, pracaMatriz);
        criarConexao(ufrb, baseBombeiros); // Via perimetral fictícia
        
        // Arvore
        arvoreEquipes.inserir(baseBombeiros);
        arvoreEquipes.inserir(baseHospital);
        arvoreEquipes.imprimirDisponiveis();
        
        logger.info("Mapa de Cruz das Almas carregado.");
    }


    private void adicionarLugarNoSistema(Lugar l) {
        lugares.add(l); 
        map.addMapMarker(new MapMarkerDot(l.getNome(), l.getCoord())); 
        grafoCidade.adicionarLugar(l); 
    }

    private void criarConexao(Lugar origem, Lugar destino) {
        double distanciaReal = calcularDistancia(origem.getCoord(), destino.getCoord());       
        grafoCidade.adicionarRota(origem, destino, distanciaReal);
        List<Coordinate> linha = new ArrayList<>();
        linha.add(origem.getCoord());
        linha.add(destino.getCoord());
        map.addMapPolygon(new MapPolygonImpl(linha));
    }
    
    private void atenderProximaSolicitacao() {
        if (filaEmergencia == null || filaEmergencia.totalDeSolicitacoes == 0) {
            JOptionPane.showMessageDialog(this, "Não há chamados pendentes. Bom trabalho!");
            return;
        }
        if (filaEmergencia.primeiro == null) return;
        Solicitacao sol = filaEmergencia.primeiro.solicitacao; 
        filaEmergencia.atenderSolicitacao(); 
        processarAtendimento(sol);
    }

    private void adicionarNaFila(Coordinate coord, String tipo) {
        String[] graus = {"1 - Baixo", "2 - Médio", "3 - Alto", "4 - CRÍTICO"};
        String grauStr = (String) JOptionPane.showInputDialog(
                this, "Qual o grau de urgência?", "Prioridade",
                JOptionPane.ERROR_MESSAGE, null, graus, graus[2]); 

        if (grauStr == null) return; // Cancelou

        int grau = Integer.parseInt(grauStr.substring(0, 1)); 
        String[] recs = Recurso.tipos; 
        String recStr = (String) JOptionPane.showInputDialog(this, "Qual recurso prioritário?", "Logística", JOptionPane.QUESTION_MESSAGE, null, recs, recs[3]);
        if (recStr == null) return;
        
        int tipoRecurso = 1;
        for(int i=0; i<recs.length; i++) { if(recs[i].equals(recStr)) tipoRecurso = i+1; }
        java.util.UUID id = java.util.UUID.randomUUID();
        
        Solicitacao novaSolicitacao = new Solicitacao(id, coord, tipo, grau, tipoRecurso);
        
        filaEmergencia.CadastrarSolicitacao(novaSolicitacao);

        MapMarkerDot marker = new MapMarkerDot("PENDENTE (" + grau + ")", coord);
        marker.setBackColor(Color.RED);
        map.addMapMarker(marker);
        marcadoresAtivos.put(id, marker);
        JOptionPane.showMessageDialog(this, "Solicitação registrada na fila de prioridade!");
    }

    
    private void processarAtendimento(Solicitacao sol) {
        
        

        Coordinate coordDesastre = sol.getCoordenadas();
        String descricao = sol.getTipoDeEmergencia();
        int recursoNecessario = sol.getTipoRecursoNecessario();

        CentroRecursos centroRecurso = hashRecursos.buscarRecursoProximo(coordDesastre, recursoNecessario);
        if (centroRecurso == null) {
            JOptionPane.showMessageDialog(this, "Sem estoque de " + Recurso.tipos[recursoNecessario-1]);
            return;
        }

        String tipoEquipeNecessaria;
        if (descricao.equals("Incêndio") || descricao.equals("Resgate") || descricao.equals("Inundação")) {
            tipoEquipeNecessaria = "Bombeiros";
        } else if (descricao.equals("Acidente de Trânsito")) {
            tipoEquipeNecessaria = "Médicos";
        } else {
            tipoEquipeNecessaria = "Logística"; 
        }

        Lugar noMaisProximoDesastre = null;
        double menorDistDesastre = Double.MAX_VALUE;
        for (Lugar l : lugares) {
            double d = calcularDistancia(coordDesastre, l.getCoord());
            if (d < menorDistDesastre) { menorDistDesastre = d; noMaisProximoDesastre = l; }
        }

        Map<Lugar, Double> distanciasDoCentro = grafoCidade.executarDijkstra(centroRecurso);
        
        Lugar melhorEquipe = null;
        double menorCaminhoTotal = Double.MAX_VALUE;

        for (Map.Entry<Lugar, Double> entrada : distanciasDoCentro.entrySet()) {
            Lugar l = entrada.getKey();
            if (l.getTipo().equalsIgnoreCase(tipoEquipeNecessaria) && l.isDisponivel()) {
                 if (entrada.getValue() < menorCaminhoTotal) {
                     menorCaminhoTotal = entrada.getValue();
                     melhorEquipe = l;
                 }
            }
        }

        if (melhorEquipe != null) {
            melhorEquipe.setDisponivel(false);
            
            arvoreEquipes.remover(melhorEquipe.getNome());
            System.out.println("Equipe removida da AVL: " + melhorEquipe.getNome());
            arvoreEquipes.imprimirDisponiveis(); // Prova visual no console
            
            
            // Base -> Centro (Pega todos os n´s da rua)
            List<Lugar> caminho1 = grafoCidade.obterMenorCaminho(melhorEquipe, centroRecurso);
            
            // Centro -> Nó perto do Desastre
            List<Lugar> caminho2 = grafoCidade.obterMenorCaminho(centroRecurso, noMaisProximoDesastre);

            List<Coordinate> rotaVisual = new ArrayList<>();
            
            
            for(Lugar l : caminho1) rotaVisual.add(l.getCoord());
            
            
            for(Lugar l : caminho2) {
                if(!rotaVisual.contains(l.getCoord())) rotaVisual.add(l.getCoord());
            }
            
            rotaVisual.add(coordDesastre);
            RotaLine desenhoRota = new RotaLine(rotaVisual);
            
            desenhoRota.setColor(Color.BLUE); 
            desenhoRota.setStroke(new java.awt.BasicStroke(3));
            map.addMapPolygon(desenhoRota); 

            String msg = "Equipe " + melhorEquipe.getNome() + " em deslocamento!\nRota real calculada.";
            JOptionPane.showMessageDialog(this, msg);

            final Lugar eq = melhorEquipe;
            new javax.swing.Timer(10000, e -> {
                eq.setDisponivel(true);
                arvoreEquipes.inserir(eq);
                System.out.println("Equipe retornou para AVL: " + eq.getNome());
                arvoreEquipes.imprimirDisponiveis();                
                map.removeMapPolygon(desenhoRota);
                ((javax.swing.Timer)e.getSource()).stop();
                MapMarkerDot marcadorVermelho = marcadoresAtivos.remove(sol.getID());
                if (marcadorVermelho != null) map.removeMapMarker(marcadorVermelho);
            }).start();

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma equipe disponível!");
        }
    }
    
    private void gerarCentrosRecursosAleatorios() {
        Random rand = new Random();
        
        double minLon = -39.1250; double maxLon = -39.0850;
        double minLat = -12.6750; double maxLat = -12.6550;

        for(int k = 0; k < 15; k++){ 
            double lat = minLat + (maxLat - minLat) * rand.nextDouble();
            double lon = minLon + (maxLon - minLon) * rand.nextDouble();
            Coordinate c = new Coordinate(lat, lon);
            
            CentroRecursos centro = new CentroRecursos("Depósito " + (k+1), c);
            
            centro.addRecurso(1, rand.nextInt(50)); 
            centro.addRecurso(2, rand.nextInt(50)); 
            centro.addRecurso(3, rand.nextInt(50)); 
            centro.addRecurso(4, rand.nextInt(50)); 
            
            MapMarkerDot markerCentro = new MapMarkerDot("Recursos " + (k+1), c);
            markerCentro.setBackColor(Color.BLUE); 
            map.addMapMarker(markerCentro);
            
            Lugar pontoConexao = null;
            double menorDistancia = Double.MAX_VALUE;
            
            for(Lugar existente : lugares) {
                double d = calcularDistancia(c, existente.getCoord());
                if(d < menorDistancia){
                    menorDistancia = d;
                    pontoConexao = existente;
                }
            }
            
            lugares.add(centro);
            grafoCidade.adicionarLugar(centro); 
            hashRecursos.addCentroRec(centro); 
            
            if (pontoConexao != null) {
                criarConexao(centro, pontoConexao); 
            }
            // ------------------------------------------------------
        }
    }
    
    private void testeVisualizacaoAVL() {
        System.out.println(">>> INICIANDO TESTE DE CARGA DA AVL <<<");
        
        // Criando equipes fictícias apenas para encher a árvore
        // Note que vou inserir fora de ordem alfabética para forçar a árvore a trabalhar
        String[] nomes = {
            "Bravo (Polícia)", "Alpha (Médicos)", "Charlie (Bombeiros)", 
            "Delta (Logística)", "Echo (Resgate)", "Foxtrot (Polícia)", 
            "Golf (Médicos)", "Hotel (Bombeiros)", "India (Logística)", 
            "Juliet (Resgate)"
        };

        for (String nome : nomes) {
            // Cria um lugar temporário só pra guardar na árvore
            Lugar l = new Lugar(nome, "Teste", new Coordinate(0,0));
            arvoreEquipes.inserir(l);
        }

        // Agora imprime a estrutura real
        arvoreEquipes.imprimirArvoreVisual();
    }
    
}
